#!/usr/bin/env node

import { createOfflineRecoveryBranch } from './offline-branch.js';

interface CliOptions {
  storePath?: string;
  agentName?: string;
  messageId?: string;
  messages?: number;
  suppressMessageIds: string[];
  suppressRanges: Array<{ fromMessageId: string; toMessageId: string }>;
  branchName?: string;
  namespace?: string;
  discordServerId?: string;
  outboxPath?: string;
  emoji?: string;
  dryRun: boolean;
}

function usage(): string {
  return `Usage:
  agent-framework-recover --store <path> --agent <name> --message-id <discord-id> [options]

Creates and activates a Chronicle recovery branch while the normal host is down,
then queues Discord reactions for addressable messages removed from awareness.
Message content is never compiled or written to the recovery outbox.

Options:
  --message-id <id|link>      Last Discord message the agent should still see
  --messages <count>          Legacy alternative: remove N context entries
  --suppress <id|link>        Suppress one Discord message; repeat or comma-separate
  --suppress-range <a>..<b>   Suppress an inclusive context range; repeatable
  --branch <name>             Recovery branch name (generated by default)
  --namespace <namespace>     Context namespace (default: agents/<agent>)
  --discord-server <id>       Override/inject the Discord MCPL server id
  --outbox <path>             Override the branch-independent outbox path
  --emoji <emoji>             Marker reaction (default: 💤)
  --dry-run                   Inspect counts/addresses without writing
  --help                      Show this help

The agent host must be stopped before running this command.`;
}

function parseArgs(args: string[]): CliOptions {
  const options: CliOptions = { dryRun: false, suppressMessageIds: [], suppressRanges: [] };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const value = () => {
      const next = args[++i];
      if (!next) throw new Error(`${arg} requires a value`);
      return next;
    };
    switch (arg) {
      case '--store': options.storePath = value(); break;
      case '--agent': options.agentName = value(); break;
      case '--message-id':
      case '--message': options.messageId = value(); break;
      case '--messages': options.messages = Number(value()); break;
      case '--suppress':
      case '--suppress-message':
        options.suppressMessageIds.push(...value().split(',').map((item) => item.trim()).filter(Boolean));
        break;
      case '--suppress-range': {
        const raw = value();
        const separator = raw.indexOf('..');
        if (separator <= 0 || separator >= raw.length - 2) {
          throw new Error('--suppress-range must be formatted as <first>..<last>');
        }
        options.suppressRanges.push({
          fromMessageId: raw.slice(0, separator),
          toMessageId: raw.slice(separator + 2),
        });
        break;
      }
      case '--branch': options.branchName = value(); break;
      case '--namespace': options.namespace = value(); break;
      case '--discord-server': options.discordServerId = value(); break;
      case '--outbox': options.outboxPath = value(); break;
      case '--emoji': options.emoji = value(); break;
      case '--dry-run': options.dryRun = true; break;
      case '--help':
      case '-h':
        console.log(usage());
        process.exit(0);
      default: throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return options;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  if (!options.storePath || !options.agentName || (!options.messageId && options.messages === undefined)) {
    throw new Error(`--store, --agent, and either --message-id or --messages are required\n\n${usage()}`);
  }

  const result = await createOfflineRecoveryBranch({
    storePath: options.storePath,
    agentName: options.agentName,
    messageId: options.messageId,
    messages: options.messages,
    suppressMessageIds: options.suppressMessageIds,
    suppressRanges: options.suppressRanges,
    branchName: options.branchName,
    namespace: options.namespace,
    discordServerId: options.discordServerId,
    outboxPath: options.outboxPath,
    emoji: options.emoji,
    dryRun: options.dryRun,
  });

  console.log(JSON.stringify({
    ...result,
    // Keep the output useful for ops without ever exposing message content.
    refs: result.refs.map(({ serverId, channelId, messageId }) => ({ serverId, channelId, messageId })),
  }, null, 2));
}

main().catch((error) => {
  console.error(`[agent-framework-recover] ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
